[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://event-buddy-b351aabbc099.herokuapp.com"

[[redirects]]
  from = "/api/*"
  to = "https://event-buddy-b351aabbc099.herokuapp.com/:splat"
  status = 200