[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://event-buddy-b351aabbc099.herokuapp.com/api"

/api/*  https://event-buddy-b351aabbc099.herokuapp.com/api/:splat  200
