[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://event-buddy-b351aabbc099.herokuapp.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://event-buddy-b351aabbc099.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }